import Footer from "./componets/Footer/Footer";
import Navbar from "./componets/Navbar/Navbar";
import "./globals.css";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="es">
            <body >
                <header>
                    <Navbar />
                </header>
                
                {children}

                <Footer />
            </body>
        </html>
    );
}
